{
    "base_diameter": 283,
    "base_height": 10,
    "outer_diameter": 89,
    "inner_diameter": 48,
    "flange_height": 155
}