{
    "base_diameter": 135,
    "base_height": 8,
    "outer_diameter": 93,
    "inner_diameter": 38,
    "flange_height": 84
}