{
    "base_diameter": 125,
    "base_height": 10,
    "outer_diameter": 93,
    "inner_diameter": 38,
    "flange_height": 173
}