{
    "base_diameter": 109,
    "base_height": 3,
    "outer_diameter": 71,
    "inner_diameter": 46,
    "flange_height": 173
}