{
    "base_diameter": 102,
    "base_height": 11,
    "outer_diameter": 99,
    "inner_diameter": 32,
    "flange_height": 180
}