{
    "base_diameter": 120,
    "base_height": 13,
    "outer_diameter": 55,
    "inner_diameter": 47,
    "flange_height": 153
}