{
    "base_diameter": 112,
    "base_height": 6,
    "outer_diameter": 76,
    "inner_diameter": 49,
    "flange_height": 82
}