{
    "base_diameter": 297,
    "base_height": 13,
    "outer_diameter": 72,
    "inner_diameter": 34,
    "flange_height": 127
}