{
    "base_diameter": 265,
    "base_height": 6,
    "outer_diameter": 90,
    "inner_diameter": 34,
    "flange_height": 87
}