{
    "base_diameter": 109,
    "base_height": 3,
    "outer_diameter": 67,
    "inner_diameter": 37,
    "flange_height": 185
}