{
    "base_diameter": 125,
    "base_height": 3,
    "outer_diameter": 50,
    "inner_diameter": 30,
    "flange_height": 162
}