{
    "base_diameter": 250,
    "base_height": 2,
    "outer_diameter": 93,
    "inner_diameter": 19,
    "flange_height": 147
}