{
    "base_diameter": 220,
    "base_height": 7,
    "outer_diameter": 90,
    "inner_diameter": 32,
    "flange_height": 67
}