{
    "base_diameter": 123,
    "base_height": 12,
    "outer_diameter": 54,
    "inner_diameter": 49,
    "flange_height": 110
}